version: "3.9"

services:
  sunspec-fakewr:
    image: python:3.11-slim
    container_name: sunspec-fakewr
    restart: unless-stopped

    volumes:
      - /share/Container/FakeWR:/app
    working_dir: /app

    command: >
      sh -c "pip install pymodbus==2.5.3 websocket-client &&
             python sunspec_fake_wr.py"

    ports:
      - "5202:5202"

    network_mode: bridge

